server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aidemo?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-bc569246cf1b4df88be84056cb97e0e9
      model-name: qwen-plus
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-bc569246cf1b4df88be84056cb97e0e9
      model-name: text-embedding-v2

logging:
  level:
    dev.langchain4j: DEBUG